SELECT 
[ID]
,[StartTime]
,[WorkOrderID]
,[PartNumber]
,[ProductionLineID]
,[PlannedParts]
,[CumulativePlannedParts]
,[ActualParts]
,[CumulativeActualParts]
,[Downtime]
,[Scrap]
,[AvgSpeed]
,[ShiftScheduleID]
,[Shift]
,[Quality]
,[Delivery]
,[QualityAndDeliveryID1]
,[QualityAndDeliveryCode1]
,[QualityAndDeliveryOccurrences1]
,[QualityAndDeliveryID2]
,[QualityAndDeliveryCode2]
,[QualityAndDeliveryOccurrences2]
,[QualityAndDeliveryID3]
,[QualityAndDeliveryCode3]
,[QualityAndDeliveryOccurrences3]
,[QualityAndDeliveryID4]
,[QualityAndDeliveryCode4]
,[QualityAndDeliveryOccurrences4]
,[Countermeasure]
,[Recovery]
,[ModifiedBy]

FROM vHourByHourMDI
WHERE DATEPART(DAY, StartTime) = DATEPART(DAY, :date)
AND ProductionLineID = :plID