SELECT [ID]
      ,[StartTime]
      ,[WorkOrderID]
      ,[PartNumber]
      ,[ProductionLineID]
      ,[PlannedParts]
      ,[ActualParts]
      ,[CumulativePlannedParts]
      ,[CumulativeActualParts]
      ,[Downtime]
      ,[Scrap]
      ,[AvgSpeed]
      ,[Recovery]
      ,[RecoveryModifiedBy]
      ,[PlannedPartsModifiedBy]
      ,[ActualPartsModifiedBy]
      ,[ShiftScheduleID]
      ,[Shift]
      ,[ProductionLineTypeID]
      ,[SanfordTime]
      ,[MoorparkTime]
      ,[SanfordCumulativePlannedParts]
      ,[MoorparkCumulativePlannedParts]
      ,[SanfordCumulativeActualParts]
      ,[MoorparkCumulativeActualParts]
FROM vHourByHourMDI
WHERE ID = :ID